### ISSUE TITLE
Consider how to handle file upload

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-rest#102]
With the current client it's not that easy to upload files. You can't quite do a `create` via the rest client. Instead you need to use the underlying library. I'm a big fan of [how superagent handles multipart requests](https://visionmedia.github.io/superagent/#multipart-requests).

I think we should consider one of 3 options:

1. Adding the ability to pass additional options for multipart file handling to a `create` call, or
2. Add an `attach` method that allows you to add files for a create call.
3. See if we can create a client side hook for handling file upload

**Comment by daffl** [comment]
I haven't tried it yet but any reason

```js
const multer  = require('multer')
const upload = multer({ dest: 'uploads/' })
const fileService = {
  create(data, params) {
    // data is the file
    return Promise.resolve({});
  }
}

function setFile(req, res, next) {
  req.body = req.file;
  next();
}

app.post('/upload', upload.single('avatar'), setFile, fileService);
```

Shouldn't work?

**Comment by daffl** [comment]
How would you normally stream it in RN? I think https://github.com/feathersjs/feathers/issues/384 might be related.

**Comment by ekryski** [comment]
Currently we are using this https://github.com/wkh237/react-native-fetch-blob. Seems to work ok with multi-part. For streaming I'm not sure. I think you could use sockets for it. That issue is definitely related.

One thing I did see with multer is they have a streaming branch in the works (`multer@next`). I really like the look of it but haven't had time to test it out just yet. How I got along that train of thought was specifically being able to transform files prior to saving them somewhere (ie. cropping before shipping to S3).

Related:

- https://github.com/badunk/multer-s3/pull/56
- https://github.com/expressjs/multer/pull/399

**Comment by daffl** [comment]
I'm going to close this in favour of continuing the discussion in the proposal for stream support at https://github.com/feathersjs/feathers/issues/609
