### ISSUE TITLE
$in: [] returning unexpected results

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers-rest#113]
This happens on the client with feathers-rest and axios:

```
.find({
  query: {
    foo: {
      $in: foos
    }
  }
});
```
With `foos = []` this produces an HTTP request with an empty query string, i.e. a plain `.find()` and thus it returns all records.

I'd expect it to actually return an emtpy array.

As a workaround i use which returns the expected result (none) for an empty `foos` array.

```
.find({
  query: {
    foo: {
      $in: [...foos, '__dummy']
    }
  }
});
```

**Comment by daffl** [comment]
This is a limitation on how query strings work and not really anything we can change. As the [qs documentation](https://www.npmjs.com/package/qs) states:

> Key with no values (such as an empty object or array) will return nothing:

```js
assert.equal(qs.stringify({ a: [] }), '');
assert.equal(qs.stringify({ a: {} }), '');
assert.equal(qs.stringify({ a: [{}] }), '');
assert.equal(qs.stringify({ a: { b: []} }), '');
assert.equal(qs.stringify({ a: { b: {}} }), '');
```

**Comment by j2L4e** [comment]
I see, thanks for clarifying.
