### ISSUE TITLE
JSON-API + feathers-rest

### ISSUE THREAD

**Issue by nicoknoll** [feathersjs/feathers-rest#115]
Hey,
I'm currently trying to implement that if the Accept header is "application/vnd.api+json" a json-api (http://jsonapi.org/) conform response is send back. First I was thinking about cloning feathers-rest and modifying it but it won't work as feathers-rest would still catch all GET, POST, PUT, etc. calls in my understanding. So there is no way to do it that clean (or is it?).

So now I'm think about rewriting the response in the formatter to be json-api conform but it feels a little bit hacky after all.

What do you think? What is the best way in you opinion?

Greets,
Nico

**Comment by zusamann** [comment]
Does this package solve your problem?
https://yarnpkg.com/en/package/feathers-hooks-jsonapify

**Comment by nicoknoll** [comment]
@zusamann Well I saw this but wasn't sure if it always returns json-api then or only if Accept header is "application/vnd.api+json". But I'll have a look - thanks!

**Comment by zusamann** [comment]
@nicoknoll it will always return json-api, you can add the conditionality of going through the header yourself

**Comment by daffl** [comment]
Yup, I think that'll do it. Thank you @zusamann !
