### ISSUE TITLE
$gte query example?

### ISSUE THREAD

**Issue by tony-kerz** [feathersjs/feathers-rest#118]
hi,

apologies in advance for potentially being dense, but i can't seem to locate the syntax for something like a `$gte` query in a rest-ful url, the following:

```
/people?$gte[age]=21
```

incurs something like:
```
Error: Invalid value [object Object]\n    at...
```
any guidance appreciated!

thanks,
tony.

**Comment by zusamann** [comment]
Your usage seems slightly incorrect, can you try using this?
```js
// old
/people?$gte[age]=21

// new
/people?age[$gte]=21
```
Also please refer to rest the docs here:
https://docs.feathersjs.com/api/databases/querying.html

**Comment by daffl** [comment]
What @zusamann said. Also keep in mind that some database might require you to convert the value to a number in a before hook (URLs are always strings and unlike JSON have no type information).
