### ISSUE TITLE
Add the ability for services to be internal only.

### ISSUE THREAD

**Issue by pierretasci** [feathersjs/feathers-rest#23]
The service and hooks abstraction in feathers is awesome and really powerful. So much in fact, that I want to use it more extensively. I want to be able to create internal only services that have useful server side logic like a file storage service or a field validator service. 

The problem becomes that I have to expose that service's CRUD methods as rest methods. I don't necessarily want to do that. So far I have taken to namespacing my internal services with an _service_name_. This is obviously not an ideal solution. 

Having peeked into the logic that hooks a service up to express, it seems like it wouldn't be hard to just skip that part if some flag is set on the service, or if the name is _service_name_ or some other construct.

Thanks!

**Comment by daffl** [comment]
I think what you are asking for is already possible using the [disable](http://docs.feathersjs.com/hooks/bundled.html#disableproviders) hook. The disable hook allows to disable access to all or specific service methods for all or specific providers or to disable it completely.

**Comment by pierretasci** [comment]
Oh yes I see now. Apologies, I should have read the docs more closely. Thanks!

**Comment by daffl** [comment]
It's a great question and granted, it is a little hidden. I created a follow-up issue in https://github.com/feathersjs/feathers-docs/issues/93 and will add it to the FAQ.

**Comment by Shadowman4205** [comment]
Hello, i have got one simiral issue.
I am using react-starter-kit. 
I use express.
I use feathers like this 

```
const api = feathers();
api.use(compress())
  .configure(hooks())
  .configure(rest())
  .configure(services)
  .configure(middleware);

module.exports = api;

const app = express();
app.use('/api/feathers', api);
```

In my application i am using 

> fetch("/api/feathers/Service"+query) (GET)

I do not have got user authentication my application can have any visitors.
When a visitor visit the site he can type "/api/feathers/Service"+query in adress bar and get some data
How i can disable this? So only the application can make this rest calls and nobody else?

**Comment by daffl** [comment]
I would remove the sub-app setup and just add the `api/` prefix to you service names and then add authentication [as documented](https://docs.feathersjs.com/api/authentication/server.html) and created by the generator. Sub-apps are definitely not recommended because they don't play very nicely with websockets or the authentication plugin.

**Comment by Shadowman4205** [comment]
What u mean remove sub-app? you mean i have to remove const app = express(); ?
And if add authentication don't i need to authenticate every user with login? (i do not have registration system as i do not need it)
