### ISSUE TITLE
Set Accept header as default

### ISSUE THREAD

**Issue by HaNdTriX** [feathersjs/feathers-rest#28]
When using feathers-rest the `Accept: application/json`-Header is not set by default.
Since it is required to get the right errors from the backend I propose to add them as a default.

From the [docs](https://github.com/feathersjs/feathers-docs/blob/master/middleware/error-handling.md#error-handling)
> **ProTip:** If you want to have the response in json format be sure to set the `Accept` header in your request to `application/json` otherwise the default error handler will return HTML.

**Comment by ekryski** [comment]
I'm pretty sure the feathers-rest adapters (request, jquery, etc.) already do this. That note is more for when people are using POSTman or curl.

**Comment by daffl** [comment]
It seems to be a pretty common mistake to forget to set the `Accept` header when trying out the API so it might be confusing to get HTML back. I don't think it would be a big change to default to `application/json` when it isn't set.

**Comment by ekryski** [comment]
Ya I can fix it in the error handler. I already did it in the feathers-authentication middleware.

**Comment by HaNdTriX** [comment]
The feathers-rest Adapter sets the 'Content-Type' to 'application/json', but not the 'Accept' header.

**Comment by ekryski** [comment]
@HaNdTriX what I was getting at is that I think some of the adapters already do set it [jQuery](https://github.com/feathersjs/feathers-rest/blob/master/src/client/jquery.js#L6) and [request](https://github.com/feathersjs/feathers-rest/blob/master/src/client/request.js#L7) I think do this themselves but you are right we are probably better off setting them explicitly ourselves.

I'm also updating the error-handler to return errors as JSON by default.

**Comment by ekryski** [comment]
FYI I've pushed feathers-errors@2.1.0 that now responding with JSON by default and will work if you provide an `Accept` or `Content-Type` header, or both.

**Comment by HaNdTriX** [comment]
Thanks! Works like a charm!
FYI: I was using [superagent](https://github.com/visionmedia/superagent) which doesn't set the `Accept` header.

**Comment by ekryski** [comment]
I've created an issue for superagent. https://github.com/feathersjs/feathers-rest/issues/29
