### ISSUE TITLE
feathers-rest returns Internal Server Error on invalid login

### ISSUE THREAD

**Issue by juodumas** [feathersjs/feathers-rest#36]
While testing auth I have noticed that feathers-rest returns `Error: Internal Server Error` on invalid login while both socket transports return `{name: "NotAuthenticated", message: "Invalid login.", code: 401, className: "not-authenticated", errors: Object}`. Here is a gist with an example: https://gist.github.com/juodumas/ef831aa1f595e7745d7e418108bea461

**Comment by daffl** [comment]
Thank you for the Gist, that helps. Having a look at it right now.

**Comment by daffl** [comment]
The problem is that you have to use [the feathers-errors error handler](http://docs.feathersjs.com/middleware/error-handling.html). If the server looks like this it should work:

```js
// npm init --yes
// npm i feathers feathers-memory feathers-authentication feathers-hooks feathers-rest feathers-socketio feathers-primus body-parser
const bodyParser = require('body-parser')
const feathers = require('feathers')
const hooks = require('feathers-hooks')
const rest = require('feathers-rest')
const socketio = require('feathers-socketio')
const primus = require('feathers-primus')
const authentication = require('feathers-authentication')
const memoryService = require('feathers-memory')
const errorHandler = require('feathers-errors/handler');

const app = feathers()
        .configure(rest())
        .configure(socketio())
        .configure(primus({transformer: 'websockets'}))
        .configure(hooks())
        .use(bodyParser.json())
        .use(bodyParser.urlencoded({extended: true}))
        .configure(authentication())
        .use(feathers.static(__dirname + '/public'))
        .use(errorHandler())

app.use('users', memoryService())
const users = app.service('users')

users.before({
  create: authentication.hooks.hashPassword('password'),
  update: authentication.hooks.hashPassword('password'),
  patch: authentication.hooks.hashPassword('password')
})

users.create({
  id: 'admin',
  email: 'admin',
  password: 'admin'
})

app.listen(3030)
```

**Comment by juodumas** [comment]
Looks like I got too trigger happy with bug reporting. Thanks for the explanation.

**Comment by daffl** [comment]
This was a great bug report. Better to report too many things than to miss an actual bug.

**Comment by ekryski** [comment]
@juodumas 💯 . You did some of the best bug reports we've seen so far. Makes it easier to track down and determine whether it is legit or not. ❤️
