### ISSUE TITLE
Fix link in README for providers docs

### ISSUE THREAD

**Issue by wkw** [feathersjs/feathers-rest#38]
I'd do a PR, but hardly seems worth it since a maintainer can edit the file right in github... :-)

The link to providers docs in README.md is 404'ing:
https://github.com/feathersjs/feathers-rest/blame/master/README.md#L11

I think it's supposed to be this:
http://docs.feathersjs.com/rest/readme.html

**Comment by daffl** [comment]
It totally is. I noticed it on the weekend and then forgot about it. Fixed now, thanks!
