### ISSUE TITLE
Support native browser fetch

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-rest#54]
From slack:

```
Chrome throws an error `TypeError: Ilegal invocation`.
While firefox `TypeError: 'fetch' called on an object that does not implement interface Window.`
```

**Comment by bedeoverend** [comment]
I ran into this issue myself, it seems binding it to the window solves the problem - i.e. my code that's resolved the issue looks something like:

```js
app.configure(rest.fetch(fetch.bind(window)));
```

**Comment by daffl** [comment]
I think #55 should fix this. It seems like it doesn't have to be bound but in the client it was bound to a different context which confused all browser implementations.
