### ISSUE TITLE
Return `error.response.json()` doesn't resolve using fetch

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers-rest#56]
An example code:
```js
app.service('/messages').create({
  text: 'Hello'
}).then(result => {
...
}).catch(error => {
return error.response.json() // Never resolves
}).then(response => {
// Never gets here
...
})
```
This is using `node-fetch` or the built-in React Native `fetch`.

**Comment by daffl** [comment]
Does

```js
app.service('/messages').create({
  text: 'Hello'
}).then(result => {
...
}).catch(error => {
return error.response.json() // Never resolves
}).catch(console.error.bind(console));
```

log anything? I'm wondering if `error.response.json()` throws (I'm not sure what it's supposed to do) or something before.

**Comment by mcchrish** [comment]
This is the closest I can get at replicating.
https://github.com/mcchrish/feathers-fetch-error
Sorry, it requires a couple of steps:
```
npm start
```
Then test by mocha:
```
mocha test/client.test.js
```
It pauses at `return error.response.json()` then mocha will timeout.

**Comment by daffl** [comment]
If you `return` something in a Promise `catch`, that promise is no longer rejected. In your example (thank you for uploading) something like

```js
app.service('/messages').create({})
      .catch(error => {
        console.log('!!!!', error.message);
        throw error;
      })
```

Works as expected. If you make sure that you have the latest version of `feathers-rest` is installed (the one that includes https://github.com/feathersjs/feathers-rest/pull/53) the error will also be converted properly to a [Feathers error](http://docs.feathersjs.com/middleware/error-handling.html) and there shouldn't be a reason for calling `error.response.json()`.

**Comment by mcchrish** [comment]
Oh, so that's what changed.
Using 1.4.* currently, while reverting 1.3.0 makes my code works.
That's why there is no need for `error.response.json()` anymore, which is pretty neat.

Thanks 👍

**Comment by daffl** [comment]
Ah sorry, I didn't think it would be a breaking change since the REST error handling (especially for fetch and jQuery) was kind of broken before but obviously it needed to be worked around then. Glad we figured it out and hopefully this fix will make things easier.
