### ISSUE TITLE
Setting hook.method should direct the request to the chosen method.

### ISSUE THREAD

**Issue by codingfriend1** [feathersjs/feathers-rest#60]
There may be cases where a request comes in as an id request so it would use get but you want to change it to use find so you can test other properties on that data before requesting it by moving the id into the find query and setting the hook.method = 'find'.

For instance:
```
find({ query: {id: '0', approved: true} })
```
Here we want to query the id but we only want approved true. In this case don't want to filter the data afterward because it's needless work on the database.

**Comment by daffl** [comment]
True, `hook.method` is the only part of the hook object that can't be modified. There might be some tricky things to deal with for making that possible. Should the other methods hooks run as well then? What if it is redirected to a method (e.g. `get` to `create`) and necessary information is missing?

I think what you are suggesting should be already possible by setting `hook.result` in a _before_ hook which will skip calling the original method (but still run all other hooks). For your example something like:

```js
app.service('myservice').before({
  get(hook) {
    const query = { id: hook.id, approved: true};

    return this.find({ query }, hook.params).then(results => {
      if(results.length === 1) {
        hook.result = results[0];
        return hook;
      }

      throw new Error('No record found');
    });
  }
});
```

**Comment by codingfriend1** [comment]
With the memory service it seems using the id in the query does not return anything.

**Comment by codingfriend1** [comment]
It seems the memory service is expecting a number for the id, but the hook id comes in as a string. However if use use the mongoose adaptor, then it wants it as a string. What do you think is the best approach to making use the id query work with any adaptor?

**Comment by daffl** [comment]
This can also be done in a hook (also, this probably won't happen when using Feathers via websockets):

```js
app.service('myservice').before(function(hook) {
  if(hook.id) {
    hook.id = parseInt(hook.id, 10);
  }
});
```

**Comment by daffl** [comment]
Thanks again for bringing this up. I'm going to close this since it is already possible with hooks and setting `hook.result` with a fairly well defined behaviour. I think we can leave it that way for now.
