### ISSUE TITLE
Sequelize Params not passed through when using REST Client

### ISSUE THREAD

**Issue by eikaramba** [feathersjs/feathers-rest#75]
In reference to this discussion https://github.com/feathersjs/feathers-sequelize/issues/12 there is now a sequelize parameter for feathers-sequelize. However when using the rest client, this parameter is never send to the server.
See here: https://github.com/feathersjs/feathers-rest/blob/master/src/client/base.js#L36

I admit i didn't testet it yet on the server side, however i guess there it might work. But still i should be able to do this on the client as well right?

example:
```
feathers().service("myService").find({
      sequelize: {
        include: [{ all: true }]
      }
    }).then(myPreciousRelations=> {
      console.log(myPreciousRelations);
    });
```

**Comment by eikaramba** [comment]
Ah and this line needs also to be changed too (only including query to params)
https://github.com/feathersjs/feathers-rest/blob/master/src/wrappers.js#L45

**Comment by daffl** [comment]
Only `params.query` will be passed between the client and the server for security reasons. If you would like to set `params.sequelize` based on query parameters you have to sanitize and map it in a [hook](https://docs.feathersjs.com/hooks/readme.html):

```js
app.service('myservice').before(function(hook) {
  const query = hook.params.query;

  hook.params.sequelize = {};
  
  if(query.someSequelizeParameter) {
    hook.params.sequelize.myParameter = sanitize(query.someSequelizeParameter);
    delete query.someSequelizeParameter;
  }
});
```
