### ISSUE TITLE
Distinct

### ISSUE THREAD

**Issue by mcnamee** [feathersjs/feathers-rest#76]
Hi, is it possible to get 'distinct' records through a rest call (e.g. With the mongoose distinct())? Is possible to Perhaps add it via a before hook?

E.g. If I have a collection full of books, and I want to get just the names of all distinct Authors

**Comment by daffl** [comment]
You could add your own query parameter and make the model call based on that query in the hook, setting `hook.result` similar to this:

```js
app.service('users').before({
  find(params) {
    if(params.query.$distinct) {
      return this.Model.find().distinct().then(data => {
        hook.result = data;
        return hook;
      });
    }
  }
});
```

**Comment by mcnamee** [comment]
Thanks so much for the quick response @daffl - By doing it this way, is my understanding correct that it would do 2 DB queries, where the second is unneeded?

**Comment by daffl** [comment]
No. If you set the result in a `before` hook the original database call is not going to happen.

**Comment by mcnamee** [comment]
Wow, great to know. Thanks again!
I'll give it a go

**Comment by mcnamee** [comment]
Hi @daffl - I ended up creating a hook like this, which seems to work a treat:

```
/*
 * Distinct Search - can only be 1 distinct at a time
 * - allows you to URI query like: books?$distinct=author
 * ============================================================
 */
exports.searchDistinct = function () {
  return function (hook) {
    let query = hook.params.query;

    // Must be a before hook
    if (hook.type !== 'before') {
      throw new Error('The \'searchDistinct\' hook should only be used as a \'before\' hook (hooks.searchDistinct).');
    }

    // Throw error when no field is provided - eg. just users?$distinct
    if (query.$distinct === '') {
     throw new Error('Missing $distinct: Which field should be distinct? (hooks.searchDistinct)');
    }

    let distinctValue = query.$distinct || null;
    if (distinctValue == null) return hook;

    // Remove $distinct param from query (preventing errors)
    delete query.$distinct;

    return new Promise((resolve, reject) => {
      this.Model.find(query).distinct(distinctValue)
        .then(data => {
          hook.result = {
            total: data.length || 0,
            data,
          };
          resolve();
        }).catch(err => reject(err));
    });
  }
}
```

**Comment by daffl** [comment]
Awesome, thank you for sharing!

Oh, btw, you can probably just `return this.Model.aggregate(args)` instead of having to create a wrapper promise.

**Comment by mcnamee** [comment]
Thanks @daffl - that's true - although I have the wrapper promise so that I can alter the `hook.result` to include a `total` and if needed, later on extend to include `$skip` and `$limit` for example.

**Comment by daffl** [comment]
What I meant is that you can write the same thing like this:

```js
/*
 * Distinct Search - can only be 1 distinct at a time
 * - allows you to URI query like: books?$distinct=author
 * ============================================================
 */
exports.searchDistinct = function () {
  return function (hook) {
    let query = hook.params.query;

    // Must be a before hook
    if (hook.type !== 'before') {
      throw new Error('The \'searchDistinct\' hook should only be used as a \'before\' hook (hooks.searchDistinct).');
    }

    // Throw error when no field is provided - eg. just users?$distinct
    if (query.$distinct === '') {
     throw new Error('Missing $distinct: Which field should be distinct? (hooks.searchDistinct)');
    }

    let distinctValue = query.$distinct || null;
    if (distinctValue == null) return hook;

    // Remove $distinct param from query (preventing errors)
    delete query.$distinct;

    var args = [
      { $match: query || {} },
      { $group: {
        _id: "$" + distinctValue,
        total: { $sum: 1 }
      }}
    ];

    return this.Model.aggregate(args)
      .then(data => {
        hook.result = {
          total: data.length || 0,
          data,
        };

        return hook;
      });
  }
}
```

I found that especially when dealing with other calls that return a promise there is usually no need to create a new promise with `new Promise((resolve, reject) => {})`

**Comment by mcnamee** [comment]
Ah hah! Very helpful, thank you!

**Comment by ekryski** [comment]
I'm going to try and keep this in mind for reference in case we want to roll this into some common hooks. cc/ @feathersjs/core-team

**Comment by eddyystop** [comment]
I've tagged this as a todo for myself.

Please comment on any enhancements, changes, etc you have in mind.

**Comment by vigalo** [comment]
Hello 
I need to create a hook like this one to rethinkdb database adapter. How can I do it?
thanks.

**Comment by vigalo** [comment]
I solved my problem 
`module.exports = function (options = {}) { 
  return function distinct(hook) {
    let query = hook.params.query;

    // Must be a before hook
    if (hook.type !== 'before') {
      throw new Error('El hook \'distinct\' sólo puede usarse como hook \'before\' (hooks.distinct).');
    }

    // Throw error when no field is provided - eg. just users?$distinct
    if (query.$distinct === '') {
      throw new Error('$distinct no encontrado: ¿Qué campo debería ser distinto? (hooks.distinct)');
    }

    let distinctValue = query.$distinct || null;
    console.log('distinctValue', distinctValue);
    if (distinctValue == null) return hook;

    // Remove $distinct param from query (preventing errors)
    delete query.$distinct;

    // Add only the field we are searching for
    query = Object.assign({ $select: distinctValue },query)

    const rethinkdbQuery = this.createQuery(query);
    const r = this.options.r;

    // In our case, disable pagination
    hook.params.paginate = false;

    // Update the query with an additional `distinct` condition
    hook.params.rethinkdb = rethinkdbQuery.distinct();
    
    return hook;
  }
};`

**Comment by vigalo** [comment]
I solved y problem like this.



`module.exports = function (options = {}) { 
  return function distinct(hook) {
    let query = hook.params.query;

    // Must be a before hook
    if (hook.type !== 'before') {
      throw new Error('El hook \'distinct\' sólo puede usarse como hook \'before\' (hooks.distinct).');
    }

    // Throw error when no field is provided - eg. just users?$distinct
    if (query.$distinct === '') {
      throw new Error('$distinct no encontrado: ¿Qué campo debería ser distinto? (hooks.distinct)');
    }

    let distinctValue = query.$distinct || null;
    console.log('distinctValue', distinctValue);
    if (distinctValue == null) return hook;

    // Remove $distinct param from query (preventing errors)
    delete query.$distinct;

    // Add only the field we are searching for
    query = Object.assign({ $select: distinctValue },query)

    const rethinkdbQuery = this.createQuery(query);
    const r = this.options.r;

    // In our case, disable pagination
    hook.params.paginate = false;

    // Update the query with an additional `distinct` condition
    hook.params.rethinkdb = rethinkdbQuery.distinct();
    
    return hook;
  }
};`
