### ISSUE TITLE
Client fails to parse json response on 204 status using fetch

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-rest#83]
### Steps to reproduce
Call a service method which returns a `204` status with no body while using the `fetch` connection - `response.json()` then fails to parse the body and throws and error.

https://jsbin.com/wacosaneqo/edit?html,console

### Expected behavior
It should return a `null` response and throw no error

### Actual behavior
Throws `Error: Unexpected end of JSON input`

### System configuration
**Operating System**:
macOS Sierra

**Browser Version**:
Chrome 54

**Comment by daffl** [comment]
Good catch. You would think `fetch` knows about this. The fix is probably to check for a 204 status code in https://github.com/feathersjs/feathers-rest/blob/master/src/client/fetch.js#L22.

**Comment by bedeoverend** [comment]
@daffl yeah I tried internally, and just adding an `if (response.status === 204)` at that line you've linked to does the trick. I'll make a PR with tests. 

Unfortunately `fetch` [knows and its considered expected behavior](https://github.com/whatwg/fetch/issues/113), though I get that how low level it is they didn't want to treat it any different just because it was JSON.
