### ISSUE TITLE
Client: Support Service Middleware / Generic Service

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-rest#91]
I'm not sure if this is something that is in the scope of `feathers-rest`, but basically it would be great if we could intercept requests before they hit the Service e.g. something like middleware for those services. Or perhaps document a standard interface for Service's to follow, so that we can provide a custom subclassed service to use instead of one of `fetch` or `superagent` etc.

My use case is deduping `fetch` requests - basically I might have a bunch of requests going off for the exact same resource i.e. same URL, headers etc. and as a simple way of ensuring they don't double up, subsequent requests made piggy back onto the request that's already gone out.

I've done this already by just wrapping up the native `fetch` function and caching requests that are already out - but would love there to be a standard pattern to do this.

**Comment by daffl** [comment]
I think this can be done at the service and hook level already. The following snippet should cache outgoing requests and return the cached request if the same request is made again while the current one is still going:

```js
const cache = {};

app.hooks({
  before(hook) {
    const key = JSON.stringify([ hook.id, hook.params, hook.data ]);

    if(cache[key]) {
      // Use the cache promise to set hook.result
      return cache[key].then(result => {
        hook.result = result;
        return hook;
      });
    } else {
      hook.cacheKey = key;
      // Create a new promise and attache the resolver functions to the hook
      cache[key] = new Promise((resolve, reject) => {
        hook.cacheResolve = resolve;
        hook.cacheReject = reject;
      });
    }
  },

  after(hook) {
    // Resolve the cache promise
    if(hook.cacheResolve) {
      delete cache[hook.cacheKey];
      hook.cacheResolve(hook.result);
    }
  },

  error(hook) {
    // Reject the cache promise
    if(hook.cacheReject) {
      delete cache[hook.cacheKey];
      hook.cacheReject(hook.error);
    }
  }
});
```

There is probably other optimizations (e.g. a small timeout to gather more requests). Eventually we'd probably want to implement a more generalized caching plugin (that works on the server and client) and also update [feathers-batch](https://github.com/feathersjs/feathers-batch) (which is somewhat related).

**Comment by bedeoverend** [comment]
Ah great, yeah that looks like it'll do the trick. I'll use that in future - thanks! I'm happy with that as a solution, and I'll keep an eye on [feathers-hooks-common](https://github.com/feathersjs/feathers-hooks-common/issues/36).

**Comment by agonbina** [comment]
@daffl it would be great to add that snippet to the client documentation. 
The `error` hook was particularly helpful for me as I was trying to do this using all kinds of things like trying to extend the services with methods that would catch errors on the request calls and then re-throw again ... it wasn't until I came across this issue that I realized you could set app level hooks 👍

**Comment by daffl** [comment]
I wrote the hook updates up [in this blog post](https://blog.feathersjs.com/feathers-application-and-error-hooks-7a5982e70024) and it will also be in the [Auk docs](https://docs.feathersjs.com/v/auk/).

**Comment by agonbina** [comment]
@daffl I was not aware of that so thanks for the references. The error hook at the app level is definitely super useful!
