### ISSUE TITLE
support axios?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-rest#94]
[axios](https://github.com/mzabriskie/axios) is becoming super popular these days. It would be nice if `feathers-rest` also support `axios`.

**Comment by daffl** [comment]
This is done now. It would be a big help if you could add a section for it to the documentation at https://github.com/feathersjs/feathers-docs/edit/master/clients/rest.md 😄

**Comment by beeplin** [comment]
sure, I could do that in a few days. :)

**Comment by beeplin** [comment]
done. https://github.com/feathersjs/feathers-docs/pull/357
