### ISSUE TITLE
Custom HTTP status code response

### ISSUE THREAD

**Issue by immanuel192** [feathersjs/feathers-rest#99]
Hi @daffl 

I would like to return the custom HTTP status. For example with PUT method, when create new entity, I will return code 201. When update existing entity then I will return the code of 200. 

How can I return the custom status code with feathers-rest?

One think I see that we can pass the res object into params in wrappers.js so that we can freely set status code for our needs.

What do you think ?

**Comment by daffl** [comment]
I think, technically, PUT shouldn't do automatic upserts. You can register your own middleware to set the status after a service though:

```js
app.use('/myservice', service, function(req, res, next) {
  const data = res.data; // service call result

  res.status(getStatusFromData(data))  ;

  next();
});
```

**Comment by immanuel192** [comment]
HI @daffl 

Thanks for your response. If we use middleware to set the status after service invoked, then the our code in service could be come more complex. Why dont we let the service to handle it custom status whenever they need?

Trung

**Comment by daffl** [comment]
What would be more complex?

As [pointed out in this FAQ](https://docs.feathersjs.com/help/faq.html#how-do-i-access-the-request-object-in-hooks-or-services) the main reason to not let the service itself do it is that they shouldn't know about how they are being accessed. A service can also be used via websockets or locally (or other non-HTTP transport mechanisms in the future) in which case setting an HTTP status code doesn't make any sense.

If you really really need it you can always add the request and response object to `params` [in a middleware](https://docs.feathersjs.com/rest/readme.html#query-route-and-middleware-parameters) but we recommend not to do that.

**Comment by immanuel192** [comment]
Thanks
